src/controllers/article.controller.js
src/repositories/article.repository.js
src/routes/notification.router.js
src/routes/point.router.js
src/services/article.service.js

- 백엔드에서 getAllArticles 기능 구현했습니다.
-
- 없음
-
-

feat: getAllArticles 구현

---

src/controllers/article.controller.js
src/repositories/article.repository.js
src/services/article.service.js

- 백엔드 API오류부분 수정하고 테스트했습니다.
- article.Controller.get위에 부분 주석처리했습니다. (아래있는 get도 주석 처리할 예정)
- 백엔드 경로가 하나인데 아래에 cardService  잘못 정의한것처럼 보입니다.
-위와같은
-
-
- P2 : 반영을 적극적으로 고려해 주시면 좋을 것 같아요 …

feat: 마켓플레이스 백엔드 api 연동

---

src/controllers/article.controller.js

> 아티클 컨트롤러에서 cardService불러오는거 articleService불러오는것으로 오타 수정
> 아티클 컨트롤러에서 cardService불러오는거 articleService불러오는것으로 오타 수정
> 없음
-
-
-

fix:API호출부 수정-아티클컨트롤러

---

src/controllers/article.controller.js
src/repositories/article.repository.js
src/services/article.service.js

- article함수에서 test를 위한 api호출 삭제했습니다.
-
-
-
-

Chore: 필요없는 api호출 삭제

---

src/db/prisma/migrations/20250527021155_/migration.sql
src/db/prisma/schema.prisma

> 교환테이블 칼럼명 수정
> 교환테이블 상태 삭제
> 오더테이블 삭제
-
-
-
-
-

Feat/db 스키마수정&시드데이터추가

---

src/repositories/notification.repository.js
src/services/notification.service.js

- 알림.서비스.js 파일 내에 에러처리 코드 추가했습니다.
- 알림.서비스.js 파일 내에 에러처리 코드 추가했습니다.
- 없음.
- 없음.
- 없음.

Feat/noti 알림기능 에러처리 코드 추가. 

---

src/controllers/article.controller.js
src/repositories/article.repository.js
src/routes/article.route.js
src/services/article.service.js

- 마켓플레이스 구매와 교환 요청, 교환 요청 취소에 관련된 엔드포인트 완성해두었습니다.
-
-
-
-

feat: 마켓플레이스 구매 & 교환 엔드포인트 완성

---

src/controllers/notification.controller.js
src/controllers/point.controller.js
src/repositories/point.repository.js
src/routes/index.js
src/routes/point.route.js
src/services/point.service.js

- 포인트 획득시 유저 테이블에 포인트 추가되는 BE api입니다.
- 기존에 작성해놨던 틀에서 세부 사항들을 변경하여 FE api와 연동하여 작동완료 확인했습니다.
- 없음.
- 없음.
- 없음.
- P3 : 이런 방법도 있을 것 같아요~ 등의 사소한 …

feat: 쿠키패치 함수 활용 FE api 연동.

---

src/repositories/card.repository.js

> 자잘한 데이터 타입 보내주는거 변환 .
-
-
-
-
-

fix:마이갤러리 API 약간 수정

---

src/controllers/article.controller.js
src/repositories/article.repository.js
src/routes/article.route.js
src/services/article.service.js

- 구매자 엔드포인트 개발하였습니다. 중간 보고로 올렸습니다. 원 커밋인 점 죄송합니다.
-
-
-
-

feat: 마켓플레이스 구매자 엔드포인트

---

src/repositories/article.repository.js

- article repository 수정했습니다.
-
-
-
-

fix:마켓플레이스 카드보유자 생성자로 수정

---

src/controllers/article.controller.js
src/repositories/article.repository.js
src/routes/article.route.js
src/services/article.service.js

- 스키마 수정에 따른 작은 수정이 있었습니다.
-
-
-
-

feat: 마켓플레이스 구매자 엔드포인트 작은 수정

---

src/repositories/article.repository.js

- 나의 포토카드 판매목록 모바일 필터부분 개수 불일치로 인한 API 리턴값 수정
- 나의 포토카드 판매목록 모바일 필터부분 개수 불일치로 인한 API 리턴값 수정
- 없음 
-
-
- P3 : 이런 방법도 있을 것 같아요~ 등의 사소한 의견입니다 …

fix:나의판매페이지 API 수정

---

src/repositories/article.repository.js

- 포토카드 상세에서 구매자가 아닌 발행자 닉네임을 가져오도록 변경했습니다.
-
-
-
-

fix: 구매자 상세 불러오기 발행자 가져오도록 수정

---

src/db/prisma/migrations/20250601043125_google_o_auth/migration.sql
src/db/prisma/schema.prisma

-유저테이블구글ID추가 및 마이그레션
-유저테이블구글ID추가 및 마이그레션
-
-
-

fix:유저테이블 구글ID 추가

---

src/controllers/article.controller.js
src/repositories/article.repository.js
src/services/article.service.js

- 구매자 교환 목록 불러오기 로직 구현했습니다.
-
-
-
-

feat: 구매자 교환 목록 불러오기 엔드포인트 구구현

---

src/config/passport.js
src/controllers/auth.controller.js
src/repositories/auth.repository.js

> 어떤 기능을 구현한건지, 이슈 대응이라면 어떤 이슈인지 PR이 열리게 된 계기와 목적을 Reviewer 들이 쉽게 이해할 수 있도록 적어 주세요  
- Google OAuth로 가입할 때 동일한 닉네임이 이미 존재할 경우 자동으로 숫자를 붙여 중복을 피하도록 개선했습니다.
- Google 로그인 콜백 후 리디렉트되는 주소의 환경 변수명을 오타로 인해 수정했습니다.
- 불필요한 콘솔 로그를 제거하고, `findByNickname` 함수 내에서 더 적절한 Prisma 쿼리 메서드로 변경하는 리팩토링을 진행했습니다.
---
- `passport.js`에 Google OAuth 신규 가입자의 닉네임 중복 체크 및 자동 숫자 suffix 기능 추가
- 닉네임 중복 시 `닉네임1`, `닉네임2` 형태로 유니크하게 생성
- `.env`에서 `CLIENT_GOOGLE_CALLBACK_PAGE_URL` 환경 변수명을 오타 수정 -> 팀 노션에 .env 페이지 업데이트 완료, 태빈님께 피알 머지후 Render.com에서 환경변수 수정 요청예정입니다.
- `console.log` 제거 및 `findByNickname` 함수에서 `findFirst` → `findUnique`로 변경 (nickname field가 unique이므로)
---
- 없음
---
> 개발 과정에서 다른 분들의 의견은 어떠한지 궁금했거나 크로스 체크가 필요하다고 …

feat: 구글 회원가입 로그인 백엔드 기능 완성

---

src/structs/auth/loginRequest.struct.js
src/structs/auth/signupRequest.struct.js

- 프론트엔드에서 비밀번호 유효성 검사 강화한거에 맞게 백엔드에서 struct 또한 수정하였습니다
-
-
-
-

feat: 로그인과 회원가입 관련 struct 유효성 검사 추가

---

src/repositories/article.repository.js
src/repositories/card.repository.js
src/services/article.service.js

- feat: 구매 엔드포인트 품절 시 로직 보완
-
-
-
-

feat: 구매 엔드포인트 품절 시 로직 보완

---

src/controllers/article.controller.js
src/repositories/article.repository.js
src/routes/article.route.js
src/services/article.service.js

chore: 주석 이름 수정

---

.gitignore

ignore> upload/ 수정

---

src/db/prisma/mocks/photoCardMocks.js
src/db/prisma/mocks/userMocks.js

-시드데이터 수정 -> 이미지 넣기 및 랭크 다양화
-시드데이터 수정 -> 모든사람 횟수3회 김수빈->50회(생성 전용 계정)
-풀받으시고 npm run seed하면 시드넣을수있습ㄴ디ㅏ
-풀받으시고 seed.js에서 
🧹 Clearing old data...
👤 Creating users...
🖼️ Creating photo cards...
📦 Creating user cards & articles...
💤 Marking 5 random SELLING cards as sold out per user...
유저만 넣고싶으면 저기 콘솔로그 크리에이팅유저 밑에 주석처리하면 딴건 안넣고 유저만 들어가게도 할수 잇습ㄴ디ㅏ
-
-
-
- Review는 특수한 케이스가 아니면 Reviewer로 지정된 시점 …

Feat/seed Fix
